django_auth_example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users import views
from users.views import insert
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 别忘记在顶部引入 include 函数
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^insert/$', insert),
    url(r'^users/recommend1/$', views.recommend1),
    url(r'^users/recommend2/$', views.recommend2),
    url(r'^users/recommend1/users/recommend1/recommend2/$', views.recommend2),
    url(r'^users/search/$', views.search),
    url(r'^users/search/recommend2/$', views.recommend2),


    # url(r'^users/showmessage/$', views.showmessage),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^showmessage/', views.showmessage, name='showmessage'),

]

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)

    class Meta(AbstractUser.Meta):
        pass


# class MYBOOK(models.Model):
#     name = models.CharField(max_length=200)
#     price = models.FloatField()
#
#     def __str__(self):
#         return self.name+':'+str(self.price)

# class Resulttable(models.Model):
#     # movieId = models.IntegerField(null=True)  # Field name made lowercase.
#     userId = models.IntegerField(null=True)  # Field name made lowercase.
#     rating = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)
#     imdbId = models.IntegerField()  # Field name made lowercase.
#     title = models.CharField(max_length=50, blank=True, null=True)
#
#     # class Meta:
#     #     managed = False
#     #     db_table = 'resulttable'
#
#     def __str__(self):
#         return self.userId+':'+self.rating


class Resulttable(models.Model):
    # movieId = models.IntegerField(null=True)  # Field name made lowercase.
    userId = models.IntegerField(null=True)  # Field name made lowercase.
    imdbId = models.IntegerField()  # Field name made lowercase.
    rating = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)
    # title = models.CharField(max_length=50, blank=True, null=True)

    # class Meta:
    #     managed = False
    #     db_table = 'resulttable'

    def __str__(self):
        return self.userId+':'+self.rating


class Insertposter(models.Model):
    userId = models.IntegerField(null=True)
    title = models.CharField(max_length=200,blank=True,null = False)
    poster = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.userId + ':' + self.poster


class Mysearch(models.Model):
    title = models.CharField(max_length=200, blank=True, null=False)
    poster = models.CharField(max_length=500, blank=True, null=True)
    imdbId = models.CharField(max_length=500, blank=True, null=True)
    link = models.CharField(max_length=500, blank=True, null=True)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

users/views.py
from django.shortcuts import render, redirect, HttpResponse

from users.models import Resulttable, Insertposter, Mysearch
from .forms import RegisterForm
from django.http import JsonResponse
import time
import numpy as np
import json
import pandas as pd
from collections import defaultdict

global tmpmatrix
tmpmatrix = np.load('my_file.npy', allow_pickle=True).item()


def register(request):
    # 只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        # 验证数据的合法性
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

            # 注册成功，跳转回首页
            return redirect('/')
    else:
        # 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()

    # 渲染模板
    # 如果用户正在访问注册页面，则渲染的是一个空的注册表单
    # 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    return render(request, 'users/register.html', context={'form': form})


def index(request):
    return render(request, 'users/..//index.html')


def check(request):
    return render((request, 'users/..//index.html'))


# def showregist(request):
#     pass


def showmessage(request):
    usermovieid = []
    usermovietitle = []
    userrate=[]
    data = Resulttable.objects.filter(userId=100001)
    for row in data:
        usermovieid.append(row.imdbId)
        userrate.append(row.rating)

    print(userrate)
    try:
        conn = get_conn()
        cur = conn.cursor()
        # Insertposter.objects.filter(userId=USERID).delete()
        for i in usermovieid:
            cur.execute('select * from moviegenre3 where imdbId = %s', i)
            rr = cur.fetchall()
            for imdbId, title, poster, link in rr:
                usermovietitle.append(title)
                print(title)

        # print(poster_result)
    finally:
        conn.close()


    # 合并
    lst = []
    length = len(usermovietitle)
    for i in range(length):
        lst.append(usermovietitle.pop(0))
        lst.append(userrate.pop(0))
    return render(request, 'users/message.html', locals())


# USERID = 1002
def recommend2(request):  # userbased
    # USERID = int(request.GET["userIdd"]) + 100000
    # Insertposter.objects.filter(userId=USERID).delete()
    # # selectMysql()
    # read_mysql_to_csv('users/static/users_resulttable.csv', USERID)  # 追加数据，提高速率
    # ratingfile = os.path.join('users/static', 'users_resulttable.csv')
    # usercf = UserBasedCF()
    # userid = str(USERID)  # 得到了当前用户的id
    # print(userid)
    # usercf.generate_dataset(ratingfile)
    # usercf.calc_user_sim()
    # usercf.recommend(userid)  # 得到doubanid号

    USERID = int(request.GET["userIdd"]) + 100000
    Insertposter.objects.filter(userId=USERID).delete()
    # selectMysql()
    read_mysql_to_csv('users/static/users_resulttable.csv', USERID)  # 追加数据，提高速率
    ratingfile = os.path.join('usersatic', 'users_resulttable.csv')
    usercf = UserBasedCF()
    userid = str(USERID)  # 得到了当前用户的id
    print(userid)
    # usercf.generate_dataset(ratingfile)
    # usercf.calc_user_sim()
    usercf.yzqFunc()  # 得到imdbId号

    try:
        conn = get_conn()
        cur = conn.cursor()
        # Insertposter.objects.filter(userId=USERID).delete()
        for i in matrix:
            cur.execute('select * from moviegenre3 where imdbId = %s', i)
            rr = cur.fetchall()
            for imdbId, title, poster in rr:
                # print(value)         #value才是真正的海报链接
                if (Insertposter.objects.filter(title=title)):
                    continue
                else:
                    Insertposter.objects.create(userId=USERID, title=title, poster=poster)

        # print(poster_result)
    finally:
        conn.close()
    # results = Insertposter.objects.all()       #从这里传递给html= Insertposter.objects.all()  # 从这里传递给html
    results = Insertposter.objects.filter(userId=USERID)
    return render(request, 'users/movieRecommend.html', locals())
    # return render(request, 'users/..//index.html', locals())


def recommend1(request):  # itembased
    # USERID = int(request.GET["userIddd"]) + 100000
    USERID = 100001
    Insertposter.objects.filter(userId=USERID).delete()
    # selectMysql()
    read_mysql_to_csv2('users/static/users_resulttable2.csv', USERID)  # 追加数据，提高速率
    ratingfile2 = os.path.join('users/static', 'users_resulttable2.csv')
    itemcf = ItemBasedCF()
    # userid = '100001'
    userid = str(USERID)  # 得到了当前用户的id
    print(userid)
    itemcf.generate_dataset(ratingfile2)
    itemcf.calc_movie_sim()
    itemcf.recommend(userid)  # 得到imdbId号

    # 先删除所有数据

    try:
        conn = get_conn()
        cur = conn.cursor()
        # Insertposter.objects.filter(userId=USERID).delete()
        for i in matrix2:
            cur.execute('select * from moviegenre3 where imdbId = %s', i)
            rr = cur.fetchall()


            for imdbId, title, poster, link in rr:
                # print(value)         #value才是真正的海报链接
                if (Insertposter.objects.filter(title=title)):
                    continue
                else:
                    Insertposter.objects.create(userId=USERID, title=title, poster=poster)

        # print(poster_result)
    finally:
        conn.close()
        results = Insertposter.objects.filter(userId=USERID)  # 从这里传递给html= Insertposter.objects.all()  # 从这里传递给html

    return render(request, 'users/movieRecommend2.html', locals())
    # return HttpResponseRedirect('movieRecommend.html', locals())


def search(request):
    Mysearch.objects.all().delete()
    i = str(request.GET["id_search"])

    print("the receive input is:")

    sql = "select * from moviegenre3 where title like '%" + i + "%'"
    print(sql)
    try:
        conn = get_conn()
        cur = conn.cursor()

        cur.execute(sql)
        j = cur.fetchall()
        print(j)
        for imdbId, title, poster, link in j:
            # print(value)         #value才是真正的海报链接
            if (Mysearch.objects.filter(imdbId=imdbId)):
                continue
            else:
                Mysearch.objects.create(title=title, poster=poster, imdbId=imdbId, link=link)

        # print(poster_result)
    finally:
        conn.close()

        results = Mysearch.objects.all()
    return render(request, 'users/movieRecommend3.html', locals())


def insert(request):
    # MOVIEID = int(request.GET["movieId"])
    global USERID
    USERID = int(request.GET["userId"]) + 100000
    # USERID = {{}}
    RATING = float(request.GET["rating"])
    IMDBID = int(request.GET["imdbId"])

    Resulttable.objects.create(userId=USERID, rating=RATING, imdbId=IMDBID)
    # print(USERID)
    # return HttpResponseRedirect('/')
    return render(request, 'index.html', {'userId': USERID, 'rating': RATING, 'imdbId': IMDBID})


import pymysql
import csv
import codecs


def get_conn():
    conn = pymysql.connect(host='localhost', port=3306, user='root', passwd='123456', db='moviedata',
                           charset='utf8')
    return conn


def query_all(cur, sql, args):
    cur.execute(sql, args)
    return cur.fetchall()


def read_mysql_to_csv(filename, user):
    with codecs.open(filename=filename, mode='w', encoding='utf-8') as f:
        write = csv.writer(f, dialect='excel')
        conn = get_conn()
        cur = conn.cursor()
        cur.execute('select * from users_resulttable')
        # sql = ('select * from users_resulttable WHERE userId = 100001')
        rr = cur.fetchall()
        # results = query_all(cur=cur, sql=sql, args=None)
        for result in rr:
            # print(result)
            write.writerow(result[:])


def read_mysql_to_csv2(filename, user):
    with codecs.open(filename=filename, mode='w', encoding='utf-8') as f:
        write = csv.writer(f, dialect='excel')
        conn = get_conn()
        cur = conn.cursor()
        cur.execute('select * from users_resulttable WHERE userId = 100001')
        results = cur.fetchall()

        # sql = ('select * from users_resulttable WHERE userId = 100001')
        # rr = cur.fetchall()
        # results = query_all(cur=cur, sql=sql, args=None)
        for result in results:
            # print(result)
            write.writerow(result[:])


import sys
import random
import math
import os
from operator import itemgetter

random.seed(0)
user_sim_mat = {}
matrix = []  # 全局变量
matrix2 = []


class UserBasedCF(object):
    ''' TopN recommendation - User Based Collaborative Filtering '''

    def __init__(self):
        self.trainset = {}  # 训练集
        self.testset = {}  # 测试集
        self.initialset = {}  # 存储要推荐的用户的信息
        self.n_sim_user = 30
        self.n_rec_movie = 10

        self.movie_popular = {}
        self.movie_count = 0  # 总电影数量

        print('Similar user number = %d' % self.n_sim_user, file=sys.stderr)
        print('recommended movie number = %d' %
              self.n_rec_movie, file=sys.stderr)

    # @staticmethod
    # def loadfile(filename):
    #     ''' load a file, return a generator. '''
    #     fp = open(filename, 'r', encoding='UTF-8')
    #     for i, line in enumerate(fp):
    #         yield line.strip('\r\n')
    #         # if i % 100000 == 0:
    #         #     print ('loading %s(%s)' % (filename, i), file=sys.stderr)
    #     fp.close()
    #     print('load %s success' % filename, file=sys.stderr)
    #
    # def initial_dataset(self, filename1):
    #     initialset_len = 0
    #     for lines in self.loadfile(filename1):
    #         users, movies, ratings = lines.split(',')
    #         self.initialset.setdefault(users, {})
    #         self.initialset[users][movies] = (ratings)
    #         initialset_len += 1
    #
    # def generate_dataset(self, filename2, pivot=1.0):
    #     ''' load rating data and split it to training set and test set '''
    #     trainset_len = 0
    #     testset_len = 0
    #
    #     for line in self.loadfile(filename2):
    #         # user, movie, rating, _ = line.split('::')
    #         user, movie, rating = line.split(',')

templates/users/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户评过的电影</title>

    <style>
        h2{
            text-align: center;
            font-family: Georgia, serif;
            font-weight: bold
        }
        li{
            list-style: none;
            text-align: center;
            {#display: inline-block;#}
        }
    </style>
</head>

<body>
<h2>Your Rates History：</h2>
<br>
<div style="text-align:center;">
<a href="http://127.0.0.1:8000/">Back</a>
</div>
<br/>
{% for dd in lst %}
    <li>
    <p>{{ dd }}</p>
    </li>

{%  endfor %}




</body>
</html>

templates/users/movieRecommend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>推荐电影页面</title>

    <style>

        li{
            list-style: none;
            display: inline-block;
        }

        #recommend2{
                position:absolute;
                left:700px;
                background-color: #008CBA;
                color: white;
                padding: 5px 12px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
            }

    </style>
</head>
<body>
<h1>和您有相似兴趣的用户也喜欢下列电影：</h1>
{% for result in results %}
    <li>
        <p>{{ result.title }}</p>
        <img src="{{ result.poster }}" alt="">
    </li>

{%  endfor %}

        <form action="users/recommend1/recommend2/" method="get">
            {% csrf_token %}
            <input type="hidden" name="userIddd" id = "userId3">
            <input type="submit" name = "viewResult" class="view"  id = "recommend2" value="查看推荐结果">
        </form>


</body>
</html>

templates/users/movieRecommend2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>推荐电影页面</title>

        <style>

        li{
            list-style: none;
            display: inline-block;
        }
    </style>
</head>
<body background="{% static 'img/logo/bkground.jpg' %}">
<h1> Our recommendation result are as follows：</h1>
<div style="text-align:center;">
<a href="http://127.0.0.1:8000/">Back</a>
<br/>
</div>>
{% for result in results %}
    <li>
        <p>{{ result.title }}</p>
        <img src="{{ result.poster }}" alt="">
    </li>

{%  endfor %}

</body>
</html>

templates/users/movieRecommend3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>推荐电影页面</title>

        <style>

        li{
            list-style: none;
            display: inline-block;
        }
    </style>
</head>
<body background="{% static 'img/logo/bkground.jpg' %}">
<h1>查找到：</h1>
<div style="text-align:center;">
<br>
<a href="http://127.0.0.1:8000/">Back</a>
<br/>
</div>>
{% for result in results %}
    <li>
        <p>{{ result.title }}</p>
        doubanid:<p>{{ result.imdbId }}</p>
        <img src="{{ result.poster }}" alt="">
    </li>

{%  endfor %}
</body>
</html>

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body background="{% static 'img/logo/bkground.jpg' %}">
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                </form>
{#                <div class="flex-center top-gap text-small">#}
{#                    <a href="login.html">已有账号登录</a>#}
{#                </div>#}
            </div>
        </div>
    </div>
</div>
</body>

</html>